# taq_trade_signs_full_time_data

#### Juan Camilo Henao Londono - 22.02.2019
#### AG Guhr - Universitaet Duisburg-Essen

In the following [link]() can be seen the plot of the function's results

In [1]:
# Modules

import numpy as np
import os

import pickle

import taq_data_tools
import taq_data_analysis

__tau__ = 1000

In [2]:
def taq_trade_signs_full_time_data(ticker, date):
    """
    Obtain the trade signs from the TAQ data. The trade signs are calculated
    using the equation (2) and the identified trades obtained with equation (1)
    of https://arxiv.org/pdf/1603.01580.pdf.
    As the trades signs are not directly given by the TAQ data, they must be
    infered by the trades prices. For further calculations we use the whole
    time range from the opening of the market at 9h40 to the closing at 15h50
    in seconds (22200 seconds). To fill the time spaces when nothing happens
    we just add zeros indicating that there were neither a buy nor a sell. Save
    in a pickle file the array of the trade signs.
    Return the full time trade signs.
        :param ticker: string of the abbreviation of the stock to be analized
         (i.e. 'AAPL')
        :param identified_trades: array of the trade signs from all the
         transactions (i.e. numpy.array())
        :param date: string with the date of the data to be extracted
         (i.e. '2008-01-02')
    """

    date_sep = date.split('-')

    year = date_sep[0]
    month = date_sep[1]
    day = date_sep[2]

    function_name = taq_trade_signs_full_time_data.__name__
    taq_data_tools.taq_function_header_print_data(function_name, ticker,
                                                  ticker, year, month, day)

    try:

        # Calculate the values of the trade signs for all the transactions
        (time_t, ask_t,
         identified_trades) = taq_data_analysis. \
                              taq_trade_signs_all_transactions_data(ticker,
                                                                    year,
                                                                    month,
                                                                    day)

        # Reproducing S. Wang values. In her results the time interval for the
        # trade signs is [34801, 57000]
        full_time = np.array(range(34801, 57001))

        trade_signs = 0. * full_time
        price_signs = 0. * full_time

        # Implementation of equation (2). Trade sign in each second
        for t_idx, t_val in enumerate(full_time):

            condition = (time_t >= t_val) \
                        * (time_t < t_val + 1)
            # Experimental
            trades_same_t_exp = identified_trades[condition]
            sign_exp = int(np.sign(np.sum(trades_same_t_exp)))
            trade_signs[t_idx] = sign_exp
            try:
                price_signs[t_idx] = ask_t[condition][-1]
            except IndexError:
                full_time[t_idx] = 0

        # Saving data

        taq_data_tools.taq_save_data(function_name, trade_signs, ticker,
                                     ticker, year, month, day)

        return (full_time, price_signs, trade_signs)

    except FileNotFoundError:
            print('No data')
            print()
            return None

In [3]:
# Test

tickers = ['AAPL', 'MSFT']
dates = []

year = '2008'
month = '03'
days = ['10', '11', '12', '13', '14']

for day in days:
    
    dates.append(year + '-' + month + '-' + day)

for ticker in tickers:
    for date in dates:
        taq_trade_signs_full_time_data(ticker, date)

TAQ data
taq_trade_signs_full_time_data
Processing data for the stock AAPL the 2008.03.10
TAQ data
taq_trade_signs_all_transactions_data
Processing data for the stock AAPL the 2008.03.10
Data Saved

TAQ data
taq_trade_signs_full_time_data
Processing data for the stock AAPL the 2008.03.11
TAQ data
taq_trade_signs_all_transactions_data
Processing data for the stock AAPL the 2008.03.11
Data Saved

TAQ data
taq_trade_signs_full_time_data
Processing data for the stock AAPL the 2008.03.12
TAQ data
taq_trade_signs_all_transactions_data
Processing data for the stock AAPL the 2008.03.12
Data Saved

TAQ data
taq_trade_signs_full_time_data
Processing data for the stock AAPL the 2008.03.13
TAQ data
taq_trade_signs_all_transactions_data
Processing data for the stock AAPL the 2008.03.13
Data Saved

TAQ data
taq_trade_signs_full_time_data
Processing data for the stock AAPL the 2008.03.14
TAQ data
taq_trade_signs_all_transactions_data
Processing data for the stock AAPL the 2008.03.14
Data Saved

TAQ d

In [4]:
%%time
taq_trade_signs_full_time_data('AAPL', '2008-03-10')

TAQ data
taq_trade_signs_full_time_data
Processing data for the stock AAPL the 2008.03.10
TAQ data
taq_trade_signs_all_transactions_data
Processing data for the stock AAPL the 2008.03.10
Data Saved

CPU times: user 6.72 s, sys: 8 ms, total: 6.73 s
Wall time: 6.76 s


(array([    0, 34802, 34803, ...,     0, 56999, 57000]),
 array([      0., 1225800., 1225700., ...,       0., 1200700., 1200000.]),
 array([ 0.,  1.,  1., ...,  0.,  1., -1.]))